#!/bin/sh
set -eu

if [ "$#" -eq 0 ]; then
    echo "Usage: script/profile <perl-program> [args...]"
    exit 2
fi

mkdir -p var/profile
export NYTPROF="${NYTPROF:-file=var/profile/nytprof.out:addpid=1}"

exec carton exec perl -d:NYTProf "$@"

