package GPForum::Bootstrap::Routes;

use strict;
use warnings;

our $VERSION = '0.001';

sub register {
    my ( undef, %input ) = @_;

    my $application = $input{application};
    my $routes      = $application->routes;
    my $root_path   = q{/};

    $routes->get($root_path)->to('Home#show')->name('home');
    $routes->get('/robots.txt')->to('Discovery#robots')->name('robots');
    $routes->get('/sitemap.xml')->to('Discovery#sitemap')->name('sitemap');
    $routes->get('/feed.atom')->to('Discovery#feed')->name('public_feed');
    $routes->get('/health')->to('Health#summary')->name('health');
    $routes->get('/health/live')->to('Health#live')->name('health_live');
    $routes->get('/health/ready')->to('Health#ready')->name('health_ready');
    $routes->get('/metrics')->to('Operations#metrics')->name('metrics');
    $routes->get('/admin')->to('Admin#dashboard')->name('admin_dashboard');
    $routes->get('/admin/users')->to('Admin#users')->name('admin_users');
    $routes->get('/admin/roles')->to('Admin#roles')->name('admin_roles');
    $routes->post('/admin/roles')
      ->to('Admin#create_role')
      ->name('admin_role_create');
    $routes->post('/admin/permissions')
      ->to('Admin#create_permission')
      ->name('admin_permission_create');
    $routes->post('/admin/roles/:role_id/permissions')
      ->to('Admin#attach_permission')
      ->name('admin_role_permission_attach');
    $routes->get('/admin/users/:user_id/roles')
      ->to('Admin#user_roles')
      ->name('admin_user_roles');
    $routes->post('/admin/users/:user_id/roles')
      ->to('Admin#bind_role')
      ->name('admin_role_bind');
    $routes->post('/admin/role-bindings/:binding_id/revoke')
      ->to('Admin#revoke_binding')
      ->name('admin_role_binding_revoke');
    $routes->get('/admin/audit')->to('Admin#audit')->name('admin_audit');
    $routes->get('/admin/jobs')->to('Admin#jobs')->name('admin_jobs');
    $routes->get('/admin/status')->to('Admin#status')->name('admin_status');
    $routes->get('/admin/privacy')
      ->to('Privacy#review')
      ->name('privacy_review');
    $routes->post('/admin/privacy/deletions/:request_id/approve')
      ->to('Privacy#approve_deletion')
      ->name('privacy_deletion_approve');
    $routes->post('/admin/privacy/deletions/:request_id/hold')
      ->to('Privacy#hold_deletion')
      ->name('privacy_deletion_hold');
    $routes->post('/admin/privacy/erasure/:job_id/run')
      ->to('Privacy#run_erasure_job')
      ->name('privacy_erasure_run');
    $routes->get('/categories')->to('Forum#categories')->name('categories');
    $routes->get('/c/:category_id')->to('Forum#category')->name('category');
    $routes->get('/t/:thread_id/:slug')
      ->to('Forum#thread')
      ->name('thread_canonical');
    $routes->get('/t/:thread_id')->to('Forum#thread')->name('thread');
    $routes->get('/new-thread')
      ->to('Forum#new_thread_form')
      ->name('new_thread');
    $routes->post('/threads')->to('Forum#create_thread')->name('thread_create');
    $routes->post('/t/:thread_id/replies')
      ->to('Forum#create_reply')
      ->name('reply_create');
    $routes->post('/t/:thread_id/read')
      ->to('Forum#mark_thread_read')
      ->name('thread_mark_read');
    $routes->get('/feed')->to('Forum#feed')->name('feed');
    $routes->get('/bookmarks')->to('Forum#bookmarks')->name('bookmarks');
    $routes->post('/t/:thread_id/bookmark')
      ->to('Forum#create_thread_bookmark')
      ->name('thread_bookmark');
    $routes->post('/t/:thread_id/bookmark/remove')
      ->to('Forum#remove_thread_bookmark')
      ->name('thread_bookmark_remove');
    $routes->post('/t/:thread_id/subscribe')
      ->to('Forum#subscribe_thread')
      ->name('thread_subscribe');
    $routes->post('/t/:thread_id/subscribe/mute')
      ->to('Forum#mute_thread_subscription')
      ->name('thread_subscription_mute');
    $routes->post('/t/:thread_id/subscribe/remove')
      ->to('Forum#unsubscribe_thread')
      ->name('thread_unsubscribe');
    $routes->post('/t/:thread_id/report')
      ->to('Forum#report_thread')
      ->name('thread_report');
    $routes->post('/p/:post_id/report')
      ->to('Forum#report_post')
      ->name('post_report');
    $routes->post('/p/:post_id/attachments')
      ->to('Attachments#upload_post')
      ->name('post_attachment_upload');
    $routes->get('/attachments/:attachment_id/download')
      ->to('Attachments#download')
      ->name('attachment_download');
    $routes->post('/u/:username/report')
      ->to('Forum#report_profile')
      ->name('profile_report');
    $routes->get('/moderation/reports')
      ->to('Moderation#reports')
      ->name('moderation_reports');
    $routes->get('/moderation/actions')
      ->to('Moderation#actions')
      ->name('moderation_actions');
    $routes->get('/moderation/suspensions')
      ->to('Moderation#suspensions')
      ->name('moderation_suspensions');
    $routes->post('/moderation/reports/:report_id/assign')
      ->to('Moderation#assign_report')
      ->name('moderation_report_assign');
    $routes->post('/moderation/reports/:report_id/release')
      ->to('Moderation#release_report')
      ->name('moderation_report_release');
    $routes->post('/moderation/reports/:report_id/resolve')
      ->to('Moderation#resolve_report')
      ->name('moderation_report_resolve');
    $routes->post('/moderation/posts/:post_id/hide')
      ->to('Moderation#hide_post')
      ->name('moderation_post_hide');
    $routes->post('/moderation/posts/:post_id/restore')
      ->to('Moderation#restore_post')
      ->name('moderation_post_restore');
    $routes->post('/moderation/threads/:thread_id/lock')
      ->to('Moderation#lock_thread')
      ->name('moderation_thread_lock');
    $routes->post('/moderation/threads/:thread_id/unlock')
      ->to('Moderation#unlock_thread')
      ->name('moderation_thread_unlock');
    $routes->post('/moderation/actions/:action_id/reverse')
      ->to('Moderation#reverse_action')
      ->name('moderation_action_reverse');
    $routes->post('/moderation/users/:user_id/suspend')
      ->to('Moderation#suspend_user')
      ->name('moderation_user_suspend');
    $routes->post('/moderation/suspensions/:suspension_id/revoke')
      ->to('Moderation#revoke_suspension')
      ->name('moderation_suspension_revoke');
    $routes->get('/notifications')
      ->to('Notifications#inbox')
      ->name('notifications');
    $routes->post('/notifications/:notification_id/read')
      ->to('Notifications#mark_read')
      ->name('notification_read');
    $routes->get('/mentions')->to('Notifications#mentions')->name('mentions');
    $routes->get('/search/autocomplete')
      ->to('Forum#search_autocomplete')
      ->name('search_autocomplete');
    $routes->get('/search')->to('Forum#search')->name('forum_search');
    $routes->get('/register')->to('Identity#register_form')->name('register');
    $routes->post('/register')
      ->to('Identity#register')
      ->name('register_submit');
    $routes->get('/login')->to('Identity#login_form')->name('login');
    $routes->post('/login')->to('Identity#login')->name('login_submit');
    $routes->get('/password/reset')
      ->to('Identity#password_reset_request_form')
      ->name('password_reset_request');
    $routes->post('/password/reset')
      ->to('Identity#request_password_reset')
      ->name('password_reset_request_submit');
    $routes->get('/password/reset/:token')
      ->to('Identity#password_reset_form')
      ->name('password_reset_form');
    $routes->post('/password/reset/complete')
      ->to('Identity#reset_password')
      ->name('password_reset_complete');
    $routes->post('/logout')->to('Identity#logout')->name('logout');
    $routes->post('/locale')->to('Identity#set_locale')->name('locale_update');
    $routes->post('/theme')->to('Identity#set_theme')->name('theme_update');
    $routes->get('/settings')->to('Identity#settings')->name('settings');
    $routes->post('/settings')
      ->to('Identity#update_settings')
      ->name('settings_update');
    $routes->post('/settings/password')
      ->to('Identity#change_password')
      ->name('settings_password_update');
    $routes->post('/settings/email')
      ->to('Identity#request_email_change')
      ->name('settings_email_update');
    $routes->get('/email/confirm/:token')
      ->to('Identity#email_confirm_form')
      ->name('email_confirm_form');
    $routes->post('/email/confirm')
      ->to('Identity#confirm_email_change')
      ->name('email_confirm');
    $routes->get('/u/:username')->to('Identity#profile')->name('profile');
    $routes->get('/privacy')
      ->to('Privacy#dashboard')
      ->name('privacy_dashboard');
    $routes->post('/privacy/export')
      ->to('Privacy#request_export')
      ->name('privacy_export_request');
    $routes->post('/privacy/deletion')
      ->to('Privacy#request_deletion')
      ->name('privacy_deletion_request');
    $routes->websocket('/realtime')->to('Realtime#stream')->name('realtime');

    return;
}

1;
