package GPForum::Bootstrap::Routes;

use strict;
use warnings;

our $VERSION = '0.001';

sub register {
    my ( undef, %input ) = @_;

    my $application = $input{application};
    my $routes      = $application->routes;
    my $root_path   = q{/};

    $routes->get($root_path)->to('Home#show')->name('home');
    $routes->get('/robots.txt')->to('Discovery#robots')->name('robots');
    $routes->get('/sitemap.xml')->to('Discovery#sitemap')->name('sitemap');
    $routes->get('/feed.atom')->to('Discovery#feed')->name('public_feed');
    $routes->get('/health')->to('Health#summary')->name('health');
    $routes->get('/health/live')->to('Health#live')->name('health_live');
    $routes->get('/health/ready')->to('Health#ready')->name('health_ready');
    $routes->get('/metrics')->to('Operations#metrics')->name('metrics');
    $routes->get('/admin')->to('Admin#dashboard')->name('admin_dashboard');
    $routes->get('/admin/users')->to('Admin#users')->name('admin_users');
    $routes->get('/admin/roles')->to('Admin#roles')->name('admin_roles');
    $routes->get('/admin/categories')
      ->to('Admin#categories')
      ->name('admin_categories');
    $routes->post('/admin/categories')
      ->to('Admin::Categories#create_category')
      ->name('admin_category_create');
    $routes->post('/admin/categories/:category_id')
      ->to('Admin::Categories#update_category')
      ->name('admin_category_update');
    $routes->post('/admin/roles')
      ->to('Admin::Catalog#create_role')
      ->name('admin_role_create');
    $routes->post('/admin/permissions')
      ->to('Admin::Catalog#create_permission')
      ->name('admin_permission_create');
    $routes->post('/admin/roles/:role_id/permissions')
      ->to('Admin::Catalog#attach_permission')
      ->name('admin_role_permission_attach');
    $routes->get('/admin/users/:user_id/roles')
      ->to('Admin#user_roles')
      ->name('admin_user_roles');
    $routes->post('/admin/users/:user_id/roles')
      ->to('Admin::Bindings#bind_role')
      ->name('admin_role_bind');
    $routes->post('/admin/role-bindings/:binding_id/revoke')
      ->to('Admin::Bindings#revoke_binding')
      ->name('admin_role_binding_revoke');
    $routes->get('/admin/audit')->to('Admin#audit')->name('admin_audit');
    $routes->get('/admin/jobs')->to('Admin#jobs')->name('admin_jobs');
    $routes->get('/admin/status')->to('Admin#status')->name('admin_status');
    $routes->get('/admin/privacy')
      ->to('Privacy::Review#review')
      ->name('privacy_review');
    $routes->post('/admin/privacy/deletions/:request_id/approve')
      ->to('Privacy::Review#approve_deletion')
      ->name('privacy_deletion_approve');
    $routes->post('/admin/privacy/deletions/:request_id/hold')
      ->to('Privacy::Review#hold_deletion')
      ->name('privacy_deletion_hold');
    $routes->post('/admin/privacy/erasure/:job_id/run')
      ->to('Privacy::Review#run_erasure_job')
      ->name('privacy_erasure_run');
    $routes->get('/categories')->to('Forum#categories')->name('categories');
    $routes->get('/c/:category_id')->to('Forum#category')->name('category');
    $routes->get('/t/:thread_id/:slug')
      ->to('Forum#thread')
      ->name('thread_canonical');
    $routes->get('/t/:thread_id')->to('Forum#thread')->name('thread');
    $routes->get('/new-thread')
      ->to('Forum#new_thread_form')
      ->name('new_thread');
    $routes->post('/threads')
      ->to('Forum::Write#create_thread')
      ->name('thread_create');
    $routes->post('/t/:thread_id/replies')
      ->to('Forum::Write#create_reply')
      ->name('reply_create');
    $routes->post('/t/:thread_id/read')
      ->to('Forum::Write#mark_thread_read')
      ->name('thread_mark_read');
    $routes->get('/feed')->to('Forum::Community#feed')->name('feed');
    $routes->get('/bookmarks')
      ->to('Forum::Community#bookmarks')
      ->name('bookmarks');
    $routes->post('/t/:thread_id/bookmark')
      ->to('Forum::Community#create_thread_bookmark')
      ->name('thread_bookmark');
    $routes->post('/t/:thread_id/bookmark/remove')
      ->to('Forum::Community#remove_thread_bookmark')
      ->name('thread_bookmark_remove');
    $routes->post('/t/:thread_id/subscribe')
      ->to('Forum::Community#subscribe_thread')
      ->name('thread_subscribe');
    $routes->post('/t/:thread_id/subscribe/mute')
      ->to('Forum::Community#mute_thread_subscription')
      ->name('thread_subscription_mute');
    $routes->post('/t/:thread_id/subscribe/remove')
      ->to('Forum::Community#unsubscribe_thread')
      ->name('thread_unsubscribe');
    $routes->post('/t/:thread_id/report')
      ->to('Forum::Community#report_thread')
      ->name('thread_report');
    $routes->post('/p/:post_id/report')
      ->to('Forum::Community#report_post')
      ->name('post_report');
    $routes->post('/p/:post_id/attachments')
      ->to('Attachments::Upload#upload_post')
      ->name('post_attachment_upload');
    $routes->get('/attachments/:attachment_id/download')
      ->to('Attachments#download')
      ->name('attachment_download');
    $routes->post('/u/:username/report')
      ->to('Forum::Community#report_profile')
      ->name('profile_report');
    $routes->get('/moderation/reports')
      ->to('Moderation#reports')
      ->name('moderation_reports');
    $routes->get('/moderation/actions')
      ->to('Moderation#actions')
      ->name('moderation_actions');
    $routes->get('/moderation/suspensions')
      ->to('Moderation#suspensions')
      ->name('moderation_suspensions');
    $routes->post('/moderation/reports/:report_id/assign')
      ->to('Moderation::Queue#assign_report')
      ->name('moderation_report_assign');
    $routes->post('/moderation/reports/:report_id/release')
      ->to('Moderation::Queue#release_report')
      ->name('moderation_report_release');
    $routes->post('/moderation/reports/:report_id/resolve')
      ->to('Moderation::Queue#resolve_report')
      ->name('moderation_report_resolve');
    $routes->post('/moderation/posts/:post_id/hide')
      ->to('Moderation::Actions#hide_post')
      ->name('moderation_post_hide');
    $routes->post('/moderation/posts/:post_id/restore')
      ->to('Moderation::Actions#restore_post')
      ->name('moderation_post_restore');
    $routes->post('/moderation/threads/:thread_id/lock')
      ->to('Moderation::Actions#lock_thread')
      ->name('moderation_thread_lock');
    $routes->post('/moderation/threads/:thread_id/unlock')
      ->to('Moderation::Actions#unlock_thread')
      ->name('moderation_thread_unlock');
    $routes->post('/moderation/actions/:action_id/reverse')
      ->to('Moderation::Actions#reverse_action')
      ->name('moderation_action_reverse');
    $routes->post('/moderation/users/:user_id/suspend')
      ->to('Moderation::Suspensions#suspend_user')
      ->name('moderation_user_suspend');
    $routes->post('/moderation/suspensions/:suspension_id/revoke')
      ->to('Moderation::Suspensions#revoke_suspension')
      ->name('moderation_suspension_revoke');
    $routes->get('/notifications')
      ->to('Notifications#inbox')
      ->name('notifications');
    $routes->post('/notifications/:notification_id/read')
      ->to('Notifications::Read#mark_read')
      ->name('notification_read');
    $routes->get('/mentions')
      ->to('Notifications::Mentions#mentions')
      ->name('mentions');
    $routes->get('/search/autocomplete')
      ->to('Forum::Search#search_autocomplete')
      ->name('search_autocomplete');
    $routes->get('/search')->to('Forum::Search#search')->name('forum_search');
    $routes->get('/register')->to('Identity#register_form')->name('register');
    $routes->post('/register')
      ->to('Identity#register')
      ->name('register_submit');
    $routes->get('/login')->to('Identity#login_form')->name('login');
    $routes->post('/login')->to('Identity#login')->name('login_submit');
    $routes->get('/password/reset')
      ->to('Identity::Password#password_reset_request_form')
      ->name('password_reset_request');
    $routes->post('/password/reset')
      ->to('Identity::Password#request_password_reset')
      ->name('password_reset_request_submit');
    $routes->get('/password/reset/:token')
      ->to('Identity::Password#password_reset_form')
      ->name('password_reset_form');
    $routes->post('/password/reset/complete')
      ->to('Identity::Password#reset_password')
      ->name('password_reset_complete');
    $routes->post('/logout')->to('Identity#logout')->name('logout');
    $routes->post('/locale')
      ->to('Identity::Settings#set_locale')
      ->name('locale_update');
    $routes->post('/theme')
      ->to('Identity::Settings#set_theme')
      ->name('theme_update');
    $routes->get('/settings')
      ->to('Identity::Settings#settings')
      ->name('settings');
    $routes->post('/settings')
      ->to('Identity::Settings#update_settings')
      ->name('settings_update');
    $routes->post('/settings/password')
      ->to('Identity::Password#change_password')
      ->name('settings_password_update');
    $routes->post('/settings/email')
      ->to('Identity::Email#request_email_change')
      ->name('settings_email_update');
    $routes->get('/email/confirm/:token')
      ->to('Identity::Email#email_confirm_form')
      ->name('email_confirm_form');
    $routes->post('/email/confirm')
      ->to('Identity::Email#confirm_email_change')
      ->name('email_confirm');
    $routes->get('/email/verify')
      ->to('Identity::Verification#email_verify_request_form')
      ->name('email_verify_request');
    $routes->post('/email/verify/request')
      ->to('Identity::Verification#request_email_verification')
      ->name('email_verify_request_submit');
    $routes->get('/email/verify/:token')
      ->to('Identity::Verification#email_verify_form')
      ->name('email_verify_form');
    $routes->post('/email/verify/complete')
      ->to('Identity::Verification#verify_email')
      ->name('email_verify');
    $routes->get('/u/:username')
      ->to('Identity::Profile#profile')
      ->name('profile');
    $routes->get('/privacy')
      ->to('Privacy#dashboard')
      ->name('privacy_dashboard');
    $routes->post('/privacy/export')
      ->to('Privacy::Requests#request_export')
      ->name('privacy_export_request');
    $routes->post('/privacy/deletion')
      ->to('Privacy::Requests#request_deletion')
      ->name('privacy_deletion_request');
    $routes->websocket('/realtime')->to('Realtime#stream')->name('realtime');

    return;
}

1;
