package main;

use strict;
use warnings;

use Const::Fast;
use Test::More;

use lib 'lib';
use lib 't/lib';

our $VERSION = '0.001';

const my $TEST_COUNT => 160;

plan tests => $TEST_COUNT;

use_ok('GPForum');
use_ok('GPForum::Config');
use_ok('GPForum::Runtime');
use_ok('GPForum::OS::Process');
use_ok('GPForum::OS::Socket');
use_ok('GPForum::Command::Migrate');
use_ok('GPForum::Command::PlatformCheck');
use_ok('GPForum::Command::QueryBudget');
use_ok('GPForum::Controller::Health');
use_ok('GPForum::Controller::Discovery');
use_ok('GPForum::Controller::Forum');
use_ok('GPForum::Controller::Identity');
use_ok('GPForum::Controller::Moderation');
use_ok('GPForum::Controller::Notifications');
use_ok('GPForum::Controller::Operations');
use_ok('GPForum::Controller::Realtime');
use_ok('GPForum::Schema');
use_ok('GPForum::Schema::Result::SchemaVersion');
use_ok('GPForum::Migration::Plan');
use_ok('GPForum::Migration::Runner');
use_ok('GPForum::Schema::Result::Attachment');
use_ok('GPForum::Schema::Result::AttachmentLink');
use_ok('GPForum::Schema::Result::AttachmentVariant');
use_ok('GPForum::Schema::Result::AuditLog');
use_ok('GPForum::Schema::Result::Bookmark');
use_ok('GPForum::Schema::Result::Category');
use_ok('GPForum::Schema::Result::CategoryStat');
use_ok('GPForum::Schema::Result::Credential');
use_ok('GPForum::Schema::Result::DeadLetter');
use_ok('GPForum::Schema::Result::DeletionAction');
use_ok('GPForum::Schema::Result::DeletionRequest');
use_ok('GPForum::Schema::Result::ErasureJob');
use_ok('GPForum::Schema::Result::EndpointQueryBudget');
use_ok('GPForum::Schema::Result::EventLog');
use_ok('GPForum::Schema::Result::ExportRequest');
use_ok('GPForum::Schema::Result::ImportFailure');
use_ok('GPForum::Schema::Result::ImportJob');
use_ok('GPForum::Schema::Result::LegacyIdMap');
use_ok('GPForum::Schema::Result::Mention');
use_ok('GPForum::Schema::Result::ModerationAction');
use_ok('GPForum::Schema::Result::Notification');
use_ok('GPForum::Schema::Result::NotificationInbox');
use_ok('GPForum::Schema::Result::NotificationPreference');
use_ok('GPForum::Schema::Result::NotificationRead');
use_ok('GPForum::Schema::Result::OutboxMessage');
use_ok('GPForum::Schema::Result::Permission');
use_ok('GPForum::Schema::Result::Plugin');
use_ok('GPForum::Schema::Result::PluginFailure');
use_ok('GPForum::Schema::Result::PluginHook');
use_ok('GPForum::Schema::Result::Post');
use_ok('GPForum::Schema::Result::PostBody');
use_ok('GPForum::Schema::Result::PostRevision');
use_ok('GPForum::Schema::Result::ProjectionGeneration');
use_ok('GPForum::Schema::Result::ProjectionOffset');
use_ok('GPForum::Schema::Result::ReputationEvent');
use_ok('GPForum::Schema::Result::Report');
use_ok('GPForum::Schema::Result::RetentionHold');
use_ok('GPForum::Schema::Result::ResourceAcl');
use_ok('GPForum::Schema::Result::Role');
use_ok('GPForum::Schema::Result::RoleBinding');
use_ok('GPForum::Schema::Result::RolePermission');
use_ok('GPForum::Schema::Result::SearchDocument');
use_ok('GPForum::Schema::Result::Session');
use_ok('GPForum::Schema::Result::Space');
use_ok('GPForum::Schema::Result::Subscription');
use_ok('GPForum::Schema::Result::Suspension');
use_ok('GPForum::Schema::Result::Thread');
use_ok('GPForum::Schema::Result::ThreadCounter');
use_ok('GPForum::Schema::Result::ThreadCounterShard');
use_ok('GPForum::Schema::Result::ThreadReadState');
use_ok('GPForum::Schema::Result::TrustScoreSnapshot');
use_ok('GPForum::Schema::Result::User');
use_ok('GPForum::Schema::Result::UserFeedItem');
use_ok('GPForum::Schema::Result::UserReadMarkerDelta');
use_ok('GPForum::Service::Password');
use_ok('GPForum::Service::SessionToken');
use_ok('GPForum::Service::Attachment::IntentBuilder');
use_ok('GPForum::Service::Attachment::Store');
use_ok('GPForum::Service::Attachment::Validator');
use_ok('GPForum::Service::Community::BookmarkStore');
use_ok('GPForum::Service::Community::FeedReader');
use_ok('GPForum::Service::Community::FeedProjector');
use_ok('GPForum::Service::Community::MentionExtractor');
use_ok('GPForum::Service::Community::MentionReader');
use_ok('GPForum::Service::Community::MentionStore');
use_ok('GPForum::Service::Community::ReputationLedger');
use_ok('GPForum::Service::Discovery::CanonicalUrl');
use_ok('GPForum::Service::Discovery::FeedBuilder');
use_ok('GPForum::Service::Discovery::MetadataBuilder');
use_ok('GPForum::Service::Discovery::RobotsPolicy');
use_ok('GPForum::Service::Discovery::SitemapBuilder');
use_ok('GPForum::Service::Discovery::VisibilityPolicy');
use_ok('GPForum::Service::Admin::AuditReview');
use_ok('GPForum::Service::Admin::PermissionGate');
use_ok('GPForum::Service::Admin::PermissionReview');
use_ok('GPForum::Service::Admin::RoleBindingStore');
use_ok('GPForum::Service::Admin::RoleCatalog');
use_ok('GPForum::Service::Identity::Registration');
use_ok('GPForum::Service::Identity::ProfileReader');
use_ok('GPForum::Service::Identity::Store');
use_ok('GPForum::Service::Moderation::ActionStore');
use_ok('GPForum::Service::Moderation::ReportStore');
use_ok('GPForum::Service::Notification::Dispatcher');
use_ok('GPForum::Service::Notification::PreferenceStore');
use_ok('GPForum::Service::Notification::SubscriptionStore');
use_ok('GPForum::Service::Operations::LocalCache');
use_ok('GPForum::Service::Operations::MetricsSnapshot');
use_ok('GPForum::Service::Operations::OSPreflight');
use_ok('GPForum::Service::Operations::QueryBudget');
use_ok('GPForum::Service::Operations::RateLimiter');
use_ok('GPForum::Service::Operations::Readiness');
use_ok('GPForum::Service::Operations::RunbookValidator');
use_ok('GPForum::Service::Operations::RuntimeSizing');
use_ok('GPForum::Service::Portability::ExportBundleBuilder');
use_ok('GPForum::Service::Portability::ImportJobStore');
use_ok('GPForum::Service::Portability::ImportManifestValidator');
use_ok('GPForum::Service::Portability::LegacyIdMapper');
use_ok('GPForum::Service::Plugin::FailureRecorder');
use_ok('GPForum::Service::Plugin::HookDispatcher');
use_ok('GPForum::Service::Plugin::ManifestValidator');
use_ok('GPForum::Service::Plugin::Registry');
use_ok('GPForum::Service::Privacy::DataRightsReview');
use_ok('GPForum::Service::Privacy::DeletionWorkflow');
use_ok('GPForum::Service::Privacy::RetentionHoldStore');
use_ok('GPForum::Service::Forum::ThreadComposer');
use_ok('GPForum::Service::Forum::ThreadStore');
use_ok('GPForum::Service::Forum::CategoryReader');
use_ok('GPForum::Service::Forum::HomePageReader');
use_ok('GPForum::Service::Forum::PageWindow');
use_ok('GPForum::Service::Forum::PostReader');
use_ok('GPForum::Service::Forum::PostPosition');
use_ok('GPForum::Service::Forum::ReadState');
use_ok('GPForum::Service::Forum::ThreadReader');
use_ok('GPForum::Service::Forum::ThreadDetailReader');
use_ok('GPForum::Service::Forum::PostComposer');
use_ok('GPForum::Service::Forum::PostStore');
use_ok('GPForum::Service::Outbox::Dispatcher');
use_ok('GPForum::Service::Outbox::DeadLetterRecorder');
use_ok('GPForum::Service::Outbox::DomainEventTransport');
use_ok('GPForum::Service::Outbox::MessageBuilder');
use_ok('GPForum::Service::Projection::OffsetTracker');
use_ok('GPForum::Service::Projection::GenerationManager');
use_ok('GPForum::Service::Realtime::ChannelAuthorizer');
use_ok('GPForum::Service::Realtime::ConnectionRegistry');
use_ok('GPForum::Service::Realtime::Hub');
use_ok('GPForum::Service::Search::DocumentBuilder');
use_ok('GPForum::Service::Search::Indexer');
use_ok('GPForum::Service::Search::Searcher');
use_ok('GPForum::Worker::Handler::CacheInvalidation');
use_ok('GPForum::Worker::Handler::AttachmentScanning');
use_ok('GPForum::Worker::Handler::MediaProcessing');
use_ok('GPForum::Worker::Handler::NotificationDispatch');
use_ok('GPForum::Worker::Handler::SearchIndexing');
use_ok('GPForum::Worker::IdempotentJobRunner');
use_ok('GPForum::Worker::MinionRegistrar');
use_ok('GPForum::Test::MigrationDbh');
use_ok('GPForum::Test::MigrationStorage');
use_ok('GPForum::Test::MigrationSchema');
use_ok('GPForum::Test::QueryBudgetResultSet');
use_ok('GPForum::Test::QueryBudgetSchema');

1;
